addSbtPlugin("com.geirsson"      % "sbt-scalafmt"           % "1.5.1")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"        % "2.2.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"           % "0.9.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"   % "0.9.2")
addSbtPlugin("net.vonbuchholtz"  % "sbt-dependency-check"   % "0.2.8")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"          % "0.9.0")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"             % "2.6.20")
